export const theme = {
  colors: {
    primary: '#2D8A4E',
    primaryLight: '#E8F5EE',
    primaryDark: '#1A5C33',
    accent: '#F5A623',
    background: '#F7F9F7',
    surface: '#FFFFFF',
    surfaceAlt: '#F0F4F1',
    text: '#1A2E1F',
    textSecondary: '#5A7A62',
    textMuted: '#9DB5A3',
    border: '#E0EDE4',
    danger: '#E53935',
    dangerLight: '#FDECEA',
    success: '#2D8A4E',
    white: '#FFFFFF',
  },
  radius: {
    sm: 8,
    md: 14,
    lg: 20,
    xl: 28,
    full: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  shadow: {
    sm: {
      shadowColor: '#1A5C33',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 3,
    },
    md: {
      shadowColor: '#1A5C33',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 16,
      elevation: 6,
    },
  },
};