# Metadata
sonar.organization=kt-cpu
sonar.projectKey=kt-cpu_CesiZen_1_Front
sonar.projectVersion=1.0.0
sonar.projectEncoding=UTF-8

# Language et outils
sonar.language=ts

# Source
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Exclude
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,**/*.config.ts,**/*.config.js,vite.config.ts

# Quality Gate
sonar.qualityGate.wait=false