name: 01-2 - Integration - SonarCloud Analysis

on:
  workflow_call:

jobs:
  QualityBack:
    name: SonarQube Backend (.NET)
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Backend coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: back-coverage-report
          path: ./coverage

      - name: SonarQube Scan (Backend)
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
          SONAR_HOST_URL: http://localhost:9000
        with:
          args: >
            -Dsonar.projectKey=CesiZen_Back
            -Dsonar.sources=CesiZen.API,CesiZen.Domain,CesiZen.Infrastructure
            -Dsonar.tests=CesiZen.Tests
            -Dsonar.cs.opencover.reportsPaths=coverage/**/coverage.opencover.xml
            -Dsonar.coverage.exclusions=**/Migrations/**,**/Program.cs,**/*Dto*.cs
            -Dsonar.exclusions=**/Migrations/**,**/bin/**,**/obj/**
            -Dsonar.branch.name=${{ github.ref_name }}

  QualityFront:
    name: SonarQube Frontend (React)
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Frontend coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: front-coverage-report
          path: CesiZen.Web/cesizen.web.client/coverage

      - name: SonarQube Scan (Frontend)
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
          SONAR_HOST_URL: http://localhost:9000
        with:
          projectBaseDir: CesiZen.Web/cesizen.web.client
          args: >
            -Dsonar.projectKey=CesiZen_Front
            -Dsonar.branch.name=${{ github.ref_name }}
