name: 01-2 - Integration - SonarQube Analysis

on:
  workflow_call:

jobs:
  QualityBack:
    name: SonarQube Backend (.NET)
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Backend coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: back-coverage-report
          path: ./coverage

      - name: Determine branch name
        id: branch
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "name=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarQube Begin
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet sonarscanner begin \
            /k:"CesiZen-Back" \
            /d:sonar.host.url="http://localhost:9000" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN_BACK }}" \
            /d:sonar.branch.name="${{ steps.branch.outputs.name }}" \
            /d:sonar.cs.opencover.reportsPaths="coverage/**/coverage.opencover.xml" \
            /d:sonar.coverage.exclusions="**/Migrations/**,**/Program.cs,**/*Dto*.cs" \
            /d:sonar.exclusions="**/Migrations/**,**/bin/**,**/obj/**" \
            /d:sonar.qualityGate.wait=true

      - name: Build
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet build CesiZen.API.sln --no-incremental

      - name: SonarQube End
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN_BACK }}"

  QualityFront:
    name: SonarQube Frontend (React)
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Frontend coverage artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: front-coverage-report
          path: CesiZen.Web/cesizen.web.client/coverage

      - name: Determine branch name
        id: branch
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "name=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: SonarQube Scan (Frontend)
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          SONAR_HOST_URL: http://localhost:9000
        with:
          projectBaseDir: CesiZen.Web/cesizen.web.client
          args: >
            -Dsonar.projectKey=CesiZen-Front
            -Dsonar.branch.name=${{ steps.branch.outputs.name }}
            -Dsonar.qualityGate.wait=true
